version: '3.8'

services:
  arc380-ros:
    image: adrlaboratory/arc380-ros:v1.1.0
    container_name: arc380-ros
    environment:
      - ROS_HOSTNAME=arc380-ros
      - ROS_MASTER_URI=http://ros-core:11311
    volumes:
      - ./src:/root/arc380_s24/src
    depends_on:
      - ros-core
      - novnc
    tty: true
    stdin_open: true

  ros-core:
    image: adrlaboratory/arc380-ros:v1.1.0
    container_name: ros-core
    ports:
      - "11311:11311" # ROS Core
    command:
      - roscore

  ros-bridge:
    image: adrlaboratory/arc380-ros:v1.1.0
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-core:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch


  novnc:
    image: theasp/novnc:latest
    container_name: novnc
    environment:
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
      - RUN_XTERM=no
    ports:
      - "8080:8080" # noVNC Web interface
